# Generated by Django 4.1.4 on 2023-02-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='blog-thumbnail/'),
        ),
    ]
