# Generated by Django 4.1.4 on 2023-01-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='demo.jpeg', upload_to='profile-images/'),
        ),
    ]
